src/AdminBundle/Form/Type/UserFormType.php
<?php

namespace AdminBundle\Form\Type;

use EntityBundle\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotNull;

class UserFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['data'];
        $builder
            ->add('name', TextType::class, [
                'label' => 'user.label.name',
            ])
            ->add('jobTitle', TextType::class, [
                'label' => 'user.label.job_title',
            ])
            ->add('email', EmailType::class, [
                'label' => 'user.label.email',
            ])
            ->add('role', ChoiceType::class, [
                'placeholder' => 'user.label.role_placeholder',
                'multiple' => true,
                'required'    => false,
                'label'       => 'user.label.role',
                'mapped'      => false,
                'choices'     => $this->getRoles(),
                'data'        => $user->getRoles(),
                'constraints' => new NotNull(['groups' => 'user_create', 'message' => 'user.role.required']),
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'user.label.submit',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class'        => User::class,
                'validation_groups' => 'user_create',
            ]);
    }

    private function getRoles()
    {
        return [
            'Content Writer'  => 'ROLE_CONTENT_WRITER',
            'Sales Team'      => 'SALES_TEAM',
            'Ad ops'          => 'AD_OPS',
            'Lead Journalist' => 'ROLE_LEAD_JOURNALIST',
            'Manager'         => 'ROLE_MANAGER',
            'Account Manager' => 'ROLE_ACCOUNT_MANAGER',
        ];
    }
}

src/AdminBundle/Controller/UserController.php
<?php

namespace AdminBundle\Controller;

use AdminBundle\Form\Type\UserFormType;
use EntityBundle\Entity\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("user/")
 */
class UserController extends Controller
{
    /**
     * @Route("add", name="user_add")
     * @Template("AdminBundle:User:add.html.twig")
     * @Security("user.hasAccess('ADMIN')")
     *
     * @param Request $request
     *
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function addAction(Request $request)
    {
        $user = new User();

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(UserFormType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $password = $this->generatePassword();
            $user
                ->setUsername($user->getEmail())
                ->setEnabled(true)
                ->setRoles($form->get('role')->getData())
                ->setPlainPassword($password);

            $this->get('front.mail_sender')
                ->send($user->getEmail(), $this->get('translator')->trans('user.new_user.email_subject'), 'EmailTemplates/new_user.html.twig', [
                    'user'     => $user,
                    'password' => $password,
                    'role'     => $form->get('role')->getData(),
                ]);

            $em->persist($user);
            $em->flush();

            $this->addFlash('success', $this->get('translator')->trans('user.add.success'));

            return $this->redirectToRoute('user_list');
        }

        return [
            'form' => $form->createView(),
            'user' => $user,
        ];
    }

    /**
     * @Route("list", name="user_list")
     * @Security("user.hasAccess('ADMIN')")
     * @Template("AdminBundle:User:index.html.twig")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $users = $em->getRepository(User::class)->getUsers();

        return [
            'users' => $users,
        ];
    }

    /**
     * @Route("edit/{id}", name="user_edit")
     * @Template("AdminBundle:User:add.html.twig")
     *
     * @param User    $user
     * @param Request $request
     *
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function editAction(User $user, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(UserFormType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user->setRoles($form->get('role')->getData());

            $em->flush();

            $this->addFlash('success', $this->get('translator')->trans('user.edit.success'));

            return $this->redirectToRoute('user_list');
        }

        return [
            'form' => $form->createView(),
            'user' => $user,
        ];
    }

    /**
     * @Route("change-status/{id}", name="user_change_status")
     *
     * @param User $user
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function changeStatusAction(User $user)
    {
        if ($user->isEnabled()) {
            $user->setEnabled(false);
            $message = 'user.disable_success';
        } else {
            $user->setEnabled(true);
            $message = 'user.enable_success';
        }

        $this->getDoctrine()->getManager()->flush();

        $this->addFlash('success', $this->get('translator')->trans($message));

        return $this->redirectToRoute('user_list');
    }

    private function generatePassword()
    {
        $tokenGenerator = $this->get('fos_user.util.token_generator');

        return substr($tokenGenerator->generateToken(), 0, 12);
    }
}

src/AdminBundle/Resources/views/User/add.html.twig
{% extends 'AdminBundle::layout.html.twig' %}

{% block body %}
    <div class="right-panel">
        <div class="main-box mb-30">
            <div class="title-block">
                <h1>{{ user.id ? 'user.edit'|trans : 'user.add'|trans }}</h1>
            </div>
            <div class="main-content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 mb-30 mt-30">
                            {% include 'AdminBundle::flash_messages.html.twig' %}
                            {{ form_start(form) }}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group mb-30">
                                            {{ form_label(form.name) }}<span class="has-error">*</span>
                                            {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
                                            {{ form_errors(form.name) }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group mb-30">
                                            {{ form_label(form.jobTitle) }}<span class="has-error">*</span>
                                            {{ form_widget(form.jobTitle, {'attr': {'class': 'form-control'}}) }}
                                            {{ form_errors(form.jobTitle) }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group mb-30">
                                            {{ form_label(form.email) }}<span class="has-error">*</span>
                                            {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                                            {{ form_errors(form.email) }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group mb-30">
                                            {{ form_label(form.role) }}<span class="has-error">*</span>
                                            {{ form_widget(form.role, {'attr': {'class': 'form-control chosen-select', 'data-placeholder': 'user.label.role_placeholder'|trans}}) }}
                                            {{ form_errors(form.role) }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 col-md-offset-4">
                                        {{ form_widget(form.submit, {'attr': {'class': 'btn light-green btn-lg btn-block mb-20'}}) }}
                                    </div>
                                </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/AdminBundle/Resources/views/User/edit.html.twig
{% extends 'AdminBundle::layout.html.twig' %}

{% block body %}
    <div class="right-panel">
        <div class="main-box mb-30">
            <div class="title-block">
                <h1>{{ 'edit.profile'|trans }}</h1>
            </div>
            <div class="main-content">
                <div class="container-fluid">
                    <div class="row">
                        {% include "AdminBundle::flash_messages.html.twig" %}
                        <div class="col-lg-8 col-lg-offset-2 mb-30">
                            <div class="page-title">{{ 'label.edit.profile'|trans }}</div>
                            {{ form_start(form) }}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group mb-30">
                                        {{ form_label(form.name) }} <span class="has-error">*</span>
                                        {{ form_widget(form.name, {'attr': {'class' : 'form-control'}}) }}
                                        {{ form_errors(form.name) }}
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mb-30">
                                        {{ form_label(form.email) }}<span class="has-error">*</span>
                                        {{ form_widget(form.email, {'attr': {'class' : 'form-control'}}) }}
                                        {{ form_errors(form.email) }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mb-30">
                                        {{ form_label(form.jobTitle) }}<span class="has-error">*</span>
                                        {{ form_widget(form.jobTitle, {'attr': {'class' : 'form-control'}}) }}
                                        {{ form_errors(form.jobTitle) }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    {{ form_widget(form.submit, {'attr': {'class' : 'btn light-green btn-lg btn-block mb-20'}}) }}
                                </div>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/AdminBundle/Resources/views/User/index.html.twig
{% extends 'AdminBundle::layout.html.twig' %}

{% block body %}
    <div class="right-panel">
        <div class="main-box mb-30">
            <div class="title-block">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>{{ 'page.heading.backoffice.users_list'|trans }}</h1>
                    </div>
                    <div class="col-sm-6 responsive-align-left">
                        <a href="{{ path('user_add') }}" class="btn dark-grey btn-icon">
                            {{ 'user.add'|trans }}
                        </a>
                    </div>
                </div>
            </div>
            <div class="main-content pd-20">
                {% include 'AdminBundle::flash_messages.html.twig' %}
                <div class="table-responsive custom-table">
                    <table class="table table-bordered table-striped">
                        <tr class="table-headings">
                            <th class="text-center">{{ 'page.heading.backoffice.users.name'|trans }}</th>
                            <th class="text-center">{{ 'page.heading.backoffice.users.job_title'|trans }}</th>
                            <th class="text-center">{{ 'page.heading.backoffice.users.email'|trans }}</th>
                            <th class="text-center">{{ 'page.heading.backoffice.users.role'|trans }}</th>
                            <th class="text-center listing-action-btns">{{ 'listings.heading.action'|trans }}</th>
                        </tr>
                        {% for user in users %}
                            <tr>
                                <td class="text-center">
                                    <span class="responsive-label">{{ 'page.heading.backoffice.users.name'|trans }}</span>
                                    <span class="responsive-data">{{ user.name }}</span>
                                </td>
                                <td class="text-center">
                                    <span class="responsive-label">{{ 'page.heading.backoffice.users.job_title'|trans }}</span>
                                    <span class="responsive-data">{{ user.jobTitle }}</span>
                                </td>
                                <td class="text-center">
                                    <span class="responsive-label">{{ 'page.heading.backoffice.users.email'|trans }}</span>
                                    <span class="responsive-data">{{ user.email }}</span>
                                </td>
                                <td class="text-center">
                                    <span class="responsive-label">{{ 'page.heading.backoffice.users.role'|trans }}</span>
                                    <span class="responsive-data">
                                        {% for role in user.roles %}
                                            {{ role }}{% if not loop.last %},{% endif %}
                                        {% endfor %}
                                    </span>
                                </td>
                                <td class="text-center">
                                    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn light-blue btn-icon" title="{{ 'user.edit'|trans }}">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                    {% if user.enabled %}
                                        <a href="{{ path('user_change_status', {'id': user.id}) }}" class="btn dark-blue btn-icon" title="{{ 'user.disable'|trans }}">
                                            <i class="fa fa fa-ban"></i>
                                        </a>
                                    {% else %}
                                        <a href="{{ path('user_change_status', {'id': user.id}) }}" class="btn light-blue btn-icon" title="{{ 'user.enable'|trans }}">
                                            <i class="fa fa-check"></i>
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5" class="text-center">{{ 'list.no_records_found'|trans }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}